DROP DATABASE IF EXISTS backendwebshop;

CREATE DATABASE backendwebshop;

USE backendwebshop;

CREATE TABLE `users` (
    id int AUTO_INCREMENT PRIMARY KEY,
    username varchar(100) NOT NULL,
    password varchar(100) NOT NULL,
    email varchar(40) NOT NULL
);



INSERT INTO users (username, password, email) VALUES
('admin1', 'adminadmin1', 'admin1@gmail.com');

CREATE table inhoud (
    id MEDIUMINT NULL AUTO_INCREMENT PRIMARY KEY,
    titel VARCHAR(100) NOT NULL,
    soort ENUM('paperback', 'e-book') NOT NULL,
    omschrijving VARCHAR(150) NOT NULL,
    paginas INT NULL,
    genres ENUM('horror','thriller', 'educatief', 'muziek', 'fantasie', 'misdaad/mysterie', 'avontuur/actie') NOT NULL,
    prijs DECIMAL(5,2) NOT NULL,
    auteur VARCHAR(30) NOT NULL
);

INSERT INTO inhoud (titel, soort, omschrijving, paginas, genres, prijs, auteur) VALUES
-- Horror
('Het Spookhuis', 'paperback', 'Een angstaanjagend verhaal over een verlaten huis.', 320, 'horror', 19.99, 'J. van Dalen'),
('De Nachtbrenger', 'e-book', 'Duistere krachten komen tot leven in de nacht.', 280, 'horror', 12.99, 'M. de Groot'),
('Bloedmaan', 'paperback', 'Een dorp wordt geteisterd door een bloederige vloek.', 350, 'horror', 21.50, 'S. van Leeuwen'),
('Schaduwen in het Bos', 'e-book', 'Iets kwaadaardigs schuilt tussen de bomen.', 265, 'horror', 10.99, 'L. Bakker'),
('De Laatste Zucht', 'paperback', 'Overleven in een wereld vol monsters.', 410, 'horror', 22.99, 'K. Jansen'),
('Het Masker', 'e-book', 'Een mysterieus masker brengt de dood.', 230, 'horror', 9.99, 'F. Willems'),
('Zwarte Ogen', 'paperback', 'Een meisje wordt achtervolgd door haar verleden.', 300, 'horror', 18.99, 'T. de Boer'),
('De Kelder', 'e-book', 'Wat leeft er onder het huis?', 190, 'horror', 8.99, 'R. Vos'),
('Doodse Stilte', 'paperback', 'Een dorp waar niemand meer spreekt.', 275, 'horror', 17.50, 'E. van Dam'),
('Het Offer', 'e-book', 'Een ritueel loopt gruwelijk mis.', 210, 'horror', 11.50, 'G. Kuipers'),
('De Vloek van de Molen', 'paperback', 'Een oude molen herbergt een geheim.', 340, 'horror', 20.99, 'A. Mulder'),
('Demonenbloed', 'e-book', 'Een strijd tegen innerlijke demonen.', 260, 'horror', 13.25, 'C. de Vries'),
('Het Zesde Zintuig', 'paperback', 'Een jongen ziet dingen die anderen niet zien.', 295, 'horror', 16.99, 'P. van Dijk'),
('De Onzichtbare', 'e-book', 'Een onzichtbare kracht terroriseert een gezin.', 225, 'horror', 10.75, 'S. van der Meer'),
('Het Verlaten Weeshuis', 'paperback', 'Kinderen verdwijnen op mysterieuze wijze.', 360, 'horror', 23.50, 'B. Smit'),
('De Angstfabriek', 'e-book', 'Angst wordt werkelijkheid in deze fabriek.', 180, 'horror', 7.99, 'D. van den Berg'),
('Het Beest', 'paperback', 'Een monster waart rond in de stad.', 310, 'horror', 19.75, 'M. van Loon'),
('De Gedaante', 'e-book', 'Een gedaante verandert levens.', 240, 'horror', 12.50, 'J. van der Linden'),
('Het Spel', 'paperback', 'Een spel dat dodelijk afloopt.', 285, 'horror', 15.99, 'N. van der Wal'),
('De Put', 'e-book', 'Een diepe put vol geheimen.', 200, 'horror', 9.50, 'S. van der Heijden'),
('Het Donkere Pad', 'paperback', 'Een wandeling die niemand overleeft.', 330, 'horror', 21.25, 'L. van der Ven'),
('De Roep', 'e-book', 'Een stem roept uit het duister.', 215, 'horror', 11.25, 'K. van der Zee'),
('Het Portret', 'paperback', 'Een schilderij met een vloek.', 305, 'horror', 18.50, 'W. van der Pol'),
('De Spiegel', 'e-book', 'Een spiegel die je ware aard toont.', 195, 'horror', 8.75, 'R. van der Horst'),
('Het Einde', 'paperback', 'Het einde is slechts het begin.', 370, 'horror', 24.99, 'F. van der Linden'),

-- Thriller
('De Jacht', 'paperback', 'Een kat-en-muisspel met de dood.', 340, 'thriller', 20.99, 'A. de Jong'),
('Het Complot', 'e-book', 'Een complot dat de wereld verandert.', 290, 'thriller', 13.99, 'B. van Vliet'),
('De Ontvoering', 'paperback', 'Een kind verdwijnt spoorloos.', 320, 'thriller', 19.50, 'C. van Dijk'),
('De Insider', 'e-book', 'Een mol binnen de politie.', 260, 'thriller', 12.99, 'D. van Dam'),
('Het Netwerk', 'paperback', 'Een netwerk van leugens en bedrog.', 350, 'thriller', 22.50, 'E. van Leeuwen'),
('De Afrekening', 'e-book', 'Wraak kent geen genade.', 210, 'thriller', 10.99, 'F. van der Meer'),
('Het Doelwit', 'paperback', 'Een huurmoordenaar op jacht.', 300, 'thriller', 18.99, 'G. van der Linden'),
('De Schaduw', 'e-book', 'Een schaduw uit het verleden.', 230, 'thriller', 9.99, 'H. van der Wal'),
('De Code', 'paperback', 'Een code die levens kan redden of vernietigen.', 275, 'thriller', 17.50, 'I. van der Ven'),
('Het Labyrint', 'e-book', 'Een doolhof zonder uitgang.', 210, 'thriller', 11.50, 'J. van der Zee'),
('De List', 'paperback', 'Een listige dader misleidt iedereen.', 340, 'thriller', 20.99, 'K. van der Pol'),
('De Vlucht', 'e-book', 'Op de vlucht voor het verleden.', 260, 'thriller', 13.25, 'L. van der Horst'),
('De Erfenis', 'paperback', 'Een erfenis met dodelijke gevolgen.', 295, 'thriller', 16.99, 'M. van der Linden'),
('De Val', 'e-book', 'Een valstrik wordt opgezet.', 225, 'thriller', 10.75, 'N. van der Heijden'),
('Het Motief', 'paperback', 'Wat is het motief achter de moord?', 360, 'thriller', 23.50, 'O. van den Berg'),
('De Getuige', 'e-book', 'Een getuige is zijn leven niet zeker.', 180, 'thriller', 7.99, 'P. van Loon'),
('De Dader', 'paperback', 'Wie is de echte dader?', 310, 'thriller', 19.75, 'Q. van Dalen'),
('Het Alibi', 'e-book', 'Een waterdicht alibi?', 240, 'thriller', 12.50, 'R. van Dijk'),
('De Ontmaskering', 'paperback', 'De waarheid komt aan het licht.', 285, 'thriller', 15.99, 'S. van der Wal'),
('De Achtervolging', 'e-book', 'Een spannende achtervolging door de stad.', 200, 'thriller', 9.50, 'T. van der Ven'),
('Het Spel', 'paperback', 'Een dodelijk spel tussen vrienden.', 330, 'thriller', 21.25, 'U. van der Zee'),
('De Samenzwering', 'e-book', 'Een geheime samenzwering ontrafeld.', 215, 'thriller', 11.25, 'V. van der Pol'),
('De Dubbelganger', 'paperback', 'Iemand neemt je identiteit over.', 305, 'thriller', 18.50, 'W. van der Horst'),
('De Afgrond', 'e-book', 'Een sprong in het diepe.', 195, 'thriller', 8.75, 'X. van der Linden'),
('De Ontsnapping', 'paperback', 'Een ontsnapping uit een zwaarbewaakte gevangenis.', 370, 'thriller', 24.99, 'Y. van der Linden'),

-- Educatief
('De Wereld van Wiskunde', 'paperback', 'Leer alles over getallen en formules.', 220, 'educatief', 15.99, 'Dr. P. Rekens'),
('Het Heelal', 'e-book', 'Een reis door het universum.', 180, 'educatief', 12.50, 'Dr. S. Sterren'),
('Geschiedenis van Nederland', 'paperback', 'Van jagers tot nu.', 340, 'educatief', 21.99, 'Dr. H. Tijd'),
('Biologie voor Beginners', 'e-book', 'De basis van het leven uitgelegd.', 200, 'educatief', 13.99, 'Dr. L. Leven'),
('De Kunst van Taal', 'paperback', 'Taal en communicatie in de praktijk.', 260, 'educatief', 17.50, 'Dr. T. Woord'),
('Programmeren in Python', 'e-book', 'Leer programmeren met Python.', 320, 'educatief', 22.99, 'Dr. C. Code'),
('De Wereld van Chemie', 'paperback', 'Ontdek de elementen.', 280, 'educatief', 16.99, 'Dr. M. Molecuul'),
('Aardrijkskunde Atlas', 'e-book', 'De wereld in kaarten.', 210, 'educatief', 14.50, 'Dr. G. Globe'),
('Filosofie voor Iedereen', 'paperback', 'Denkers en ideeÃ«n.', 250, 'educatief', 18.99, 'Dr. F. Denken'),
('Economie in Zicht', 'e-book', 'Hoe werkt geld?', 230, 'educatief', 15.25, 'Dr. E. Euro'),
('De Taal van Muziek', 'paperback', 'Muziek als universele taal.', 190, 'educatief', 13.75, 'Dr. M. Melodie'),
('Sterrenkunde', 'e-book', 'De geheimen van het heelal.', 210, 'educatief', 14.99, 'Dr. S. Ruimte'),
('De Wereld van Planten', 'paperback', 'Alles over flora.', 270, 'educatief', 17.99, 'Dr. B. Blad'),
('De Menselijke Geest', 'e-book', 'Psychologie eenvoudig uitgelegd.', 220, 'educatief', 16.50, 'Dr. P. Psyche'),
('Techniek in de Praktijk', 'paperback', 'Van wiel tot computer.', 300, 'educatief', 19.99, 'Dr. T. Tech'),
('De Geschiedenis van Kunst', 'e-book', 'Van grotschilderingen tot nu.', 240, 'educatief', 15.99, 'Dr. K. Kunst'),
('Wiskundige Raadsels', 'paperback', 'Puzzels en breinbrekers.', 180, 'educatief', 12.99, 'Dr. R. Raadsel'),
('De Wereld van Insecten', 'e-book', 'Ontdek het kleine leven.', 200, 'educatief', 13.50, 'Dr. I. Insect'),
('De Oorsprong van Soorten', 'paperback', 'Evolutie uitgelegd.', 310, 'educatief', 20.99, 'Dr. C. Darwin'),
('De Magie van Getallen', 'e-book', 'Wiskunde is overal.', 190, 'educatief', 12.75, 'Dr. N. Nummer'),
('De Taal van Beeld', 'paperback', 'Visuele communicatie.', 260, 'educatief', 17.25, 'Dr. V. Visueel'),
('De Wereld van Dieren', 'e-book', 'Alles over fauna.', 230, 'educatief', 15.50, 'Dr. D. Dier'),
('De Kracht van Water', 'paperback', 'Water in de natuur.', 210, 'educatief', 14.99, 'Dr. W. Water'),
('De Geschiedenis van Muziek', 'e-book', 'Van klassiek tot pop.', 250, 'educatief', 18.25, 'Dr. M. Muziek'),
('De Wereld van Talen', 'paperback', 'Talen en dialecten.', 280, 'educatief', 16.75, 'Dr. T. Taal'),

-- Muziek
('De Kunst van Componeren', 'paperback', 'Leer componeren als een meester.', 210, 'muziek', 17.99, 'A. Bach'),
('Jazz door de Eeuwen', 'e-book', 'De geschiedenis van jazzmuziek.', 180, 'muziek', 13.50, 'B. Davis'),
('Rocklegendes', 'paperback', 'De grootste rockbands ooit.', 320, 'muziek', 21.99, 'C. Richards'),
('De Wereld van Klassiek', 'e-book', 'Ontdek klassieke muziek.', 200, 'muziek', 14.99, 'D. Mozart'),
('Popmuziek en Cultuur', 'paperback', 'De invloed van popmuziek.', 260, 'muziek', 18.50, 'E. Jackson'),
('Het Leven van Beethoven', 'e-book', 'Het verhaal van een genie.', 230, 'muziek', 15.25, 'F. Beethoven'),
('De Taal van Muziek', 'paperback', 'Muziek als universele taal.', 190, 'muziek', 13.75, 'G. Melodie'),
('Elektronische Muziek', 'e-book', 'Van synth tot dance.', 210, 'muziek', 14.50, 'H. Kraftwerk'),
('De Geschiedenis van Opera', 'paperback', 'Opera van toen tot nu.', 250, 'muziek', 18.99, 'I. Verdi'),
('Muzikale Innovaties', 'e-book', 'Vernieuwingen in muziek.', 220, 'muziek', 16.50, 'J. Cage'),
('De Wereld van Instrumenten', 'paperback', 'Ontdek muziekinstrumenten.', 270, 'muziek', 17.99, 'K. Strijker'),
('Het Geheim van Harmonie', 'e-book', 'Wat maakt muziek mooi?', 200, 'muziek', 13.99, 'L. Toon'),
('De Kunst van Improvisatie', 'paperback', 'Improviseren in muziek.', 230, 'muziek', 15.75, 'M. Solo'),
('De Invloed van Blues', 'e-book', 'Blues en zijn nalatenschap.', 210, 'muziek', 14.25, 'N. King'),
('Muziek en Emotie', 'paperback', 'Hoe muziek gevoelens oproept.', 260, 'muziek', 18.25, 'O. Hart'),
('De Wereld van Hip-Hop', 'e-book', 'Van Bronx tot wereldwijd.', 240, 'muziek', 15.99, 'P. Rapper'),
('De Evolutie van Dance', 'paperback', 'Dance van disco tot EDM.', 280, 'muziek', 19.50, 'Q. Beat'),
('Het Leven van Chopin', 'e-book', 'Romantiek in muziek.', 210, 'muziek', 14.75, 'R. Chopin'),
('De Kunst van Zang', 'paperback', 'Zangtechnieken en stemmen.', 220, 'muziek', 16.25, 'S. Stem'),
('De Wereld van Jazz', 'e-book', 'Jazzmuziek wereldwijd.', 230, 'muziek', 15.50, 'T. Sax'),
('Muziek en Technologie', 'paperback', 'Technologie in muziekproductie.', 250, 'muziek', 18.75, 'U. Synth'),
('De Geschiedenis van Pop', 'e-book', 'Popmuziek door de jaren heen.', 200, 'muziek', 13.25, 'V. Pop'),
('De Magie van Melodie', 'paperback', 'Wat maakt een melodie pakkend?', 210, 'muziek', 15.99, 'W. Lijn'),
('De Wereld van Drums', 'e-book', 'Alles over drummen.', 190, 'muziek', 12.99, 'X. Drum'),
('De Kunst van Luisteren', 'paperback', 'Luisteren naar muziek.', 220, 'muziek', 16.50, 'Y. Oor'),

-- Fantasie
('De Drakenvorst', 'paperback', 'Een episch avontuur met draken.', 420, 'fantasie', 24.99, 'A. Storm'),
('Het Verborgen Rijk', 'e-book', 'Een wereld vol magie en mysterie.', 380, 'fantasie', 21.50, 'B. Elfen'),
('De Zilveren Maan', 'paperback', 'Een strijd tussen licht en duister.', 410, 'fantasie', 23.99, 'C. Licht'),
('Het Magische Zwaard', 'e-book', 'Een held zoekt een legendarisch wapen.', 390, 'fantasie', 20.99, 'D. Held'),
('De Schaduwkoning', 'paperback', 'Een koning met een duister geheim.', 430, 'fantasie', 25.50, 'E. Schaduw'),
('De Elfenprinses', 'e-book', 'Een prinses met magische krachten.', 370, 'fantasie', 19.99, 'F. Elf'),
('De Toren van Tijd', 'paperback', 'Een reis door de tijd.', 400, 'fantasie', 22.99, 'G. Tijd'),
('Het Boek der Spreuken', 'e-book', 'Spreuken die de wereld veranderen.', 360, 'fantasie', 18.99, 'H. Spreuk'),
('De Verboden Stad', 'paperback', 'Een stad vol geheimen.', 390, 'fantasie', 20.75, 'I. Stad'),
('De MagiÃ«r', 'e-book', 'Een magiÃ«r op zoek naar kennis.', 380, 'fantasie', 21.25, 'J. Magie'),
('Het Kristallen Hart', 'paperback', 'Een hart van kristal met grote kracht.', 410, 'fantasie', 23.50, 'K. Kristal'),
('De Reisgenoot', 'e-book', 'Een onverwachte vriendschap.', 370, 'fantasie', 19.75, 'L. Vriend'),
('De Poortwachter', 'paperback', 'De bewaker van de poorten tussen werelden.', 400, 'fantasie', 22.50, 'M. Poort'),
('Het Geheim van de Maan', 'e-book', 'De maan verbergt een groot geheim.', 360, 'fantasie', 18.50, 'N. Maan'),
('De Vleugels van de Feniks', 'paperback', 'Een feniks herrijst uit zijn as.', 390, 'fantasie', 20.99, 'O. Feniks'),
('De IJzeren Troon', 'e-book', 'Een strijd om de macht.', 380, 'fantasie', 21.99, 'P. Troon'),
('Het Zwaard van Licht', 'paperback', 'Een zwaard dat alleen de waardige kan hanteren.', 410, 'fantasie', 23.25, 'Q. Licht'),
('De Schaduwpoort', 'e-book', 'Een poort naar een andere wereld.', 370, 'fantasie', 19.50, 'R. Poort'),
('De Gouden Draak', 'paperback', 'Een draak met een schat.', 400, 'fantasie', 22.75, 'S. Draak'),
('Het Boek van de Tijd', 'e-book', 'Tijdreizen en paradoxen.', 360, 'fantasie', 18.25, 'T. Tijd'),
('De Zwarte Tovenaar', 'paperback', 'Een tovenaar met duistere krachten.', 390, 'fantasie', 20.50, 'U. Tovenaar'),
('De Reis naar het Noorden', 'e-book', 'Een barre tocht door sneeuw en ijs.', 380, 'fantasie', 21.75, 'V. Noord'),
('Het Geheim van de Sterren', 'paperback', 'Sterren die wensen vervullen.', 410, 'fantasie', 23.99, 'W. Ster'),
('De Wachters van het Woud', 'e-book', 'Beschermers van het magische bos.', 370, 'fantasie', 19.25, 'X. Woud'),
('De Legende van de Feniks', 'paperback', 'De mythe van de onsterfelijke vogel.', 400, 'fantasie', 22.50, 'Y. Feniks'),

-- Misdaad/Mysterie
('De Verdwijning', 'paperback', 'Een onopgeloste zaak.', 320, 'misdaad/mysterie', 19.99, 'A. Inspecteur'),
('Het Raadsel van de Brug', 'e-book', 'Een mysterieus ongeluk op een brug.', 280, 'misdaad/mysterie', 15.99, 'B. Detective'),
('De Moord op Zondag', 'paperback', 'Een moordzaak in een klein dorp.', 350, 'misdaad/mysterie', 21.50, 'C. Rechercheur'),
('Het Verborgen Motief', 'e-book', 'Een motief dat niemand zag aankomen.', 265, 'misdaad/mysterie', 13.99, 'D. Motief'),
('De Dode Getuige', 'paperback', 'Een getuige wordt vermoord.', 410, 'misdaad/mysterie', 22.99, 'E. Getuige'),
('Het Spel van de Dader', 'e-book', 'Een dader speelt een gevaarlijk spel.', 230, 'misdaad/mysterie', 11.99, 'F. Dader'),
('De Schaduw van de Nacht', 'paperback', 'Een zaak in de duisternis.', 300, 'misdaad/mysterie', 18.99, 'G. Nacht'),
('Het Geheim van de Kluis', 'e-book', 'Een kluis vol geheimen.', 190, 'misdaad/mysterie', 9.99, 'H. Kluis'),
('De Verdachte', 'paperback', 'Wie is de echte verdachte?', 275, 'misdaad/mysterie', 17.50, 'I. Verdacht'),
('Het Alibi', 'e-book', 'Een waterdicht alibi?', 210, 'misdaad/mysterie', 10.99, 'J. Alibi'),
('De Ontmaskering', 'paperback', 'De waarheid komt aan het licht.', 340, 'misdaad/mysterie', 20.99, 'K. Waarheid'),
('Het Doolhof', 'e-book', 'Een mysterieus doolhof.', 260, 'misdaad/mysterie', 13.25, 'L. Doolhof'),
('De Erfenis', 'paperback', 'Een erfenis met geheimen.', 295, 'misdaad/mysterie', 16.99, 'M. Erfenis'),
('De Valstrik', 'e-book', 'Een valstrik voor de dader.', 225, 'misdaad/mysterie', 10.75, 'N. Val'),
('Het Motief', 'paperback', 'Wat is het motief achter de misdaad?', 360, 'misdaad/mysterie', 23.50, 'O. Motief'),
('De Getuige', 'e-book', 'Een getuige is zijn leven niet zeker.', 180, 'misdaad/mysterie', 7.99, 'P. Getuige'),
('De Dader', 'paperback', 'Wie is de echte dader?', 310, 'misdaad/mysterie', 19.75, 'Q. Dader'),
('Het Alibi', 'e-book', 'Een waterdicht alibi?', 240, 'misdaad/mysterie', 12.50, 'R. Alibi'),
('De Ontmaskering', 'paperback', 'De waarheid komt aan het licht.', 285, 'misdaad/mysterie', 15.99, 'S. Waarheid'),
('De Achtervolging', 'e-book', 'Een spannende achtervolging.', 200, 'misdaad/mysterie', 9.50, 'T. Achtervolg'),
('Het Spel', 'paperback', 'Een dodelijk spel.', 330, 'misdaad/mysterie', 21.25, 'U. Spel'),
('De Samenzwering', 'e-book', 'Een geheime samenzwering.', 215, 'misdaad/mysterie', 11.25, 'V. Samenzwering'),
('De Dubbelganger', 'paperback', 'Iemand neemt je identiteit over.', 305, 'misdaad/mysterie', 18.50, 'W. Dubbel'),
('De Afgrond', 'e-book', 'Een sprong in het diepe.', 195, 'misdaad/mysterie', 8.75, 'X. Diep'),
('De Ontsnapping', 'paperback', 'Een ontsnapping uit de gevangenis.', 370, 'misdaad/mysterie', 24.99, 'Y. Ontsnap'),

-- Avontuur/Actie
('De Schat van de Amazone', 'paperback', 'Een zoektocht naar een verloren schat.', 320, 'avontuur/actie', 19.99, 'A. Avontuur'),
('De Expeditie', 'e-book', 'Een gevaarlijke reis door onbekend gebied.', 280, 'avontuur/actie', 15.99, 'B. Expeditie'),
('De Storm', 'paperback', 'Overleven tijdens een orkaan.', 350, 'avontuur/actie', 21.50, 'C. Storm'),
('De Vlucht', 'e-book', 'Op de vlucht voor gevaar.', 265, 'avontuur/actie', 13.99, 'D. Vlucht'),
('De Bergbeklimmer', 'paperback', 'Een klim naar de top.', 410, 'avontuur/actie', 22.99, 'E. Klim'),
('Het Eiland', 'e-book', 'Overleven op een onbewoond eiland.', 230, 'avontuur/actie', 11.99, 'F. Eiland'),
('De Woestijnrace', 'paperback', 'Een race door de woestijn.', 300, 'avontuur/actie', 18.99, 'G. Woestijn'),
('De Jungletocht', 'e-book', 'Een tocht door de jungle.', 190, 'avontuur/actie', 9.99, 'H. Jungle'),
('De Diepzee', 'paperback', 'Avontuur onder water.', 275, 'avontuur/actie', 17.50, 'I. Diepzee'),
('De Ruimtevlucht', 'e-book', 'Een reis naar de sterren.', 210, 'avontuur/actie', 10.99, 'J. Ruimte'),
('De Ontsnapping', 'paperback', 'Een ontsnapping uit gevangenschap.', 340, 'avontuur/actie', 20.99, 'K. Ontsnapping'),
('De Achtervolging', 'e-book', 'Een spannende achtervolging.', 260, 'avontuur/actie', 13.25, 'L. Achtervolging'),
('De Schatkaart', 'paperback', 'Een mysterieuze kaart leidt naar avontuur.', 295, 'avontuur/actie', 16.99, 'M. Kaart'),
('De Val', 'e-book', 'Een valstrik in de jungle.', 225, 'avontuur/actie', 10.75, 'N. Val'),
('Het Motief', 'paperback', 'Een avontuur met een verborgen motief.', 360, 'avontuur/actie', 23.50, 'O. Motief'),
('De Getuige', 'e-book', 'Een getuige van een misdaad.', 180, 'avontuur/actie', 7.99, 'P. Getuige'),
('De Dader', 'paperback', 'Op zoek naar de dader.', 310, 'avontuur/actie', 19.75, 'Q. Dader'),
('Het Alibi', 'e-book', 'Een alibi tijdens een avontuur.', 240, 'avontuur/actie', 12.50, 'R. Alibi'),
('De Ontmaskering', 'paperback', 'De waarheid komt aan het licht.', 285, 'avontuur/actie', 15.99, 'S. Waarheid'),
('De Achtervolging', 'e-book', 'Een spannende achtervolging.', 200, 'avontuur/actie', 9.50, 'T. Achtervolg'),
('Het Spel', 'paperback', 'Een dodelijk spel.', 330, 'avontuur/actie', 21.25, 'U. Spel'),
('De Samenzwering', 'e-book', 'Een geheime samenzwering.', 215, 'avontuur/actie', 11.25, 'V. Samenzwering'),
('De Dubbelganger', 'paperback', 'Iemand neemt je identiteit over.', 305, 'avontuur/actie', 18.50, 'W. Dubbel'),
('De Afgrond', 'e-book', 'Een sprong in het diepe.', 195, 'avontuur/actie', 8.75, 'X. Diep'),
('De Ontsnapping', 'paperback', 'Een ontsnapping uit de gevangenis.', 370, 'avontuur/actie', 24.99, 'Y. Ontsnap');
